<!doctypehtml><html class="sidebar-visible no-js light"lang=en><head><meta charset=UTF-8><title>Exception handling - 100 Page Python Intro</title><meta content="text/html; charset=utf-8"http-equiv=Content-Type><meta content="Short, introductory guide for the Python programming language"name=description><meta content=width=device-width,initial-scale=1 name=viewport><meta content=#ffffff name=theme-color><meta content="100 Page Python Intro"property=og:title><meta content=website property=og:type><meta content="Short, introductory guide for the Python programming language"property=og:description><meta content=https://learnbyexample.github.io/100_page_python_intro/ property=og:url><meta content=https://raw.githubusercontent.com/learnbyexample/100_page_python_intro/main/images/py_intro_ls.png property=og:image><meta content=1280 property=og:image:width><meta content=720 property=og:image:height><meta content=summary_large_image property=twitter:card><meta content=@learn_byexample property=twitter:site><link href=favicon.svg rel=icon><link rel="shortcut icon"href=favicon.png><link href=css/variables.css rel=stylesheet><link href=css/general.css rel=stylesheet><link href=css/chrome.css rel=stylesheet><link href=FontAwesome/css/font-awesome.css rel=stylesheet><link href=fonts/fonts.css rel=stylesheet><link href=highlight.css rel=stylesheet><link href=tomorrow-night.css rel=stylesheet><link href=ayu-highlight.css rel=stylesheet><link href=style.css rel=stylesheet><body><script>var path_to_root = "";
            var default_theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "navy" : "light";</script><script>try {
                var theme = localStorage.getItem('mdbook-theme');
                var sidebar = localStorage.getItem('mdbook-sidebar');

                if (theme.startsWith('"') && theme.endsWith('"')) {
                    localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
                }

                if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                    localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
                }
            } catch (e) { }</script><script>var theme;
            try { theme = localStorage.getItem('mdbook-theme'); } catch(e) { }
            if (theme === null || theme === undefined) { theme = default_theme; }
            var html = document.querySelector('html');
            html.classList.remove('no-js')
            html.classList.remove('light')
            html.classList.add(theme);
            html.classList.add('js');</script><script>var html = document.querySelector('html');
            var sidebar = 'hidden';
            if (document.body.clientWidth >= 1080) {
                try { sidebar = localStorage.getItem('mdbook-sidebar'); } catch(e) { }
                sidebar = sidebar || 'visible';
            }
            html.classList.remove('sidebar-visible');
            html.classList.add("sidebar-" + sidebar);</script><nav aria-label="Table of contents"class=sidebar id=sidebar><div class=sidebar-scrollbox><ol class=chapter><li class="chapter-item expanded affix"><a href=cover.html>Cover</a><li class="chapter-item expanded affix"><a href=buy.html>Buy PDF/EPUB versions</a><li class="chapter-item expanded"><a href=preface.html><strong aria-hidden=true>1.</strong> Preface</a><li class="chapter-item expanded"><a href=introduction.html><strong aria-hidden=true>2.</strong> Introduction</a><li class="chapter-item expanded"><a href=numeric-data-types.html><strong aria-hidden=true>3.</strong> Numeric data types</a><li class="chapter-item expanded"><a href=strings-and-user-input.html><strong aria-hidden=true>4.</strong> Strings and user input</a><li class="chapter-item expanded"><a href=defining-functions.html><strong aria-hidden=true>5.</strong> Defining functions</a><li class="chapter-item expanded"><a href=control-structures.html><strong aria-hidden=true>6.</strong> Control structures</a><li class="chapter-item expanded"><a href=importing-and-creating-modules.html><strong aria-hidden=true>7.</strong> Importing and creating modules</a><li class="chapter-item expanded"><a href=installing-modules-and-virtual-environments.html><strong aria-hidden=true>8.</strong> Installing modules and Virtual environments</a><li class="chapter-item expanded"><a class=active href=exception-handling.html><strong aria-hidden=true>9.</strong> Exception handling</a><li class="chapter-item expanded"><a href=debugging.html><strong aria-hidden=true>10.</strong> Debugging</a><li class="chapter-item expanded"><a href=testing.html><strong aria-hidden=true>11.</strong> Testing</a><li class="chapter-item expanded"><a href=tuple-and-sequence-operations.html><strong aria-hidden=true>12.</strong> Tuple and Sequence operations</a><li class="chapter-item expanded"><a href=list.html><strong aria-hidden=true>13.</strong> List</a><li class="chapter-item expanded"><a href=mutability.html><strong aria-hidden=true>14.</strong> Mutability</a><li class="chapter-item expanded"><a href=dict.html><strong aria-hidden=true>15.</strong> Dict</a><li class="chapter-item expanded"><a href=set.html><strong aria-hidden=true>16.</strong> Set</a><li class="chapter-item expanded"><a href=text-processing.html><strong aria-hidden=true>17.</strong> Text processing</a><li class="chapter-item expanded"><a href=comprehensions-and-generator-expressions.html><strong aria-hidden=true>18.</strong> Comprehensions and Generator expressions</a><li class="chapter-item expanded"><a href=dealing-with-files.html><strong aria-hidden=true>19.</strong> Dealing with files</a><li class="chapter-item expanded"><a href=executing-external-commands.html><strong aria-hidden=true>20.</strong> Executing external commands</a><li class="chapter-item expanded"><a href=command-line-arguments.html><strong aria-hidden=true>21.</strong> Command line arguments</a></li><br><hr><li class="chapter-item expanded"><i class="fa fa-github"id=git-repository-button></i><a href=https://github.com/learnbyexample/100_page_python_intro>   Source code</a><li class="chapter-item expanded"><i class="fa fa-home"id=home-button></i><a href=https://learnbyexample.github.io/>   My Blog</a><li class="chapter-item expanded"><i class="fa fa-book"id=book-button></i><a href=https://learnbyexample.github.io/books/>   My Books</a><li class="chapter-item expanded"><i class="fa fa-envelope"id=mail-button></i><a href=https://learnbyexample.gumroad.com/l/learnbyexample-weekly>   learnbyexample weekly</a><li class="chapter-item expanded"><i class="fa fa-twitter"id=twitter-button></i><a href=https://twitter.com/learn_byexample>   Twitter</a></ol></div><div class=sidebar-resize-handle id=sidebar-resize-handle></div></nav><div class=page-wrapper id=page-wrapper><div class=page><div id=menu-bar-hover-placeholder></div><div class="menu-bar sticky bordered"id=menu-bar><div class=left-buttons><button aria-label="Toggle Table of Contents"title="Toggle Table of Contents"aria-controls=sidebar class=icon-button id=sidebar-toggle type=button><i class="fa fa-bars"></i></button><button aria-label="Change theme"title="Change theme"aria-controls=theme-list aria-expanded=false aria-haspopup=true class=icon-button id=theme-toggle type=button><i class="fa fa-paint-brush"></i></button><ul aria-label=Themes class=theme-popup id=theme-list role=menu><li role=none><button class=theme id=light role=menuitem>Light (default)</button><li role=none><button class=theme id=rust role=menuitem>Rust</button><li role=none><button class=theme id=coal role=menuitem>Coal</button><li role=none><button class=theme id=navy role=menuitem>Navy</button><li role=none><button class=theme id=ayu role=menuitem>Ayu</button></ul><button aria-label="Toggle Searchbar"title="Search. (Shortkey: s)"aria-controls=searchbar aria-expanded=false aria-keyshortcuts=S class=icon-button id=search-toggle type=button><i class="fa fa-search"></i></button></div><h1 class=menu-title>100 Page Python Intro</h1><div class=right-buttons><a aria-label=Blog href=https://learnbyexample.github.io title=Blog> <i class="fa fa-home"id=home-button></i> </a><a aria-label=Twitter href=https://twitter.com/learn_byexample title=Twitter> <i class="fa fa-twitter"id=twitter-button></i> </a><a aria-label="Git repository"title="Git repository"href=https://github.com/learnbyexample/100_page_python_intro> <i class="fa fa-github"id=git-repository-button></i> </a></div></div><div class=hidden id=search-wrapper><form class=searchbar-outer id=searchbar-outer><input placeholder="Search this book ..."aria-controls=searchresults-outer aria-describedby=searchresults-header id=searchbar name=searchbar type=search></form><div class="searchresults-outer hidden"id=searchresults-outer><div class=searchresults-header id=searchresults-header></div><ul id=searchresults></ul></div></div><script>document.getElementById('sidebar-toggle').setAttribute('aria-expanded', sidebar === 'visible');
                    document.getElementById('sidebar').setAttribute('aria-hidden', sidebar !== 'visible');
                    Array.from(document.querySelectorAll('#sidebar a')).forEach(function(link) {
                        link.setAttribute('tabIndex', sidebar === 'visible' ? 0 : -1);
                    });</script><div class=content id=content><main><div class=sidetoc><nav class=pagetoc></nav></div><h1 id=exception-handling><a class=header href=#exception-handling>Exception handling</a></h1><p>This chapter will discuss different types of errors and how to handle some of the them within the program gracefully. You'll also see how to raise exceptions programmatically.<h2 id=syntax-errors><a class=header href=#syntax-errors>Syntax errors</a></h2><p>Quoting from <a href=https://docs.python.org/3/tutorial/errors.html>docs.python: Errors and Exceptions</a>:<blockquote><p>There are (at least) two distinguishable kinds of errors: <em>syntax errors</em> and <em>exceptions</em></blockquote><p>Here's an example program with syntax errors:<pre><code class=language-python># syntax_error.py
print('hello')

def main():
    num = 5
    total = num + 09 
    print(total)

main)
</code></pre><p>The above code is using an unsupported syntax for a numerical value. Note that the syntax check happens before any code is executed, which is why you don't see the output for the <code>print('hello')</code> statement. Can you spot the rest of the syntax issues in the above program?<pre><code class=language-bash>$ python3.13 syntax_error.py
  File "/home/learnbyexample/Python/programs/syntax_error.py", line 5
    total = num + 09 
                  ^
SyntaxError: leading zeros in decimal integer literals are not permitted;
             use an 0o prefix for octal integers
</code></pre><h2 id=try-except><a class=header href=#try-except>try-except</a></h2><p>Exceptions happen when something goes wrong during the code execution. For example, passing a wrong data type to a function, dividing a number by <code>0</code> and so on. Such errors are typically difficult or impossible to determine just by looking at the code.<pre><code class=language-python>>>> int('42')
42
>>> int('42x')
Traceback (most recent call last):
  File "&LTpython-input-1>", line 1, in &LTmodule>
    int('42x')
    ~~~^^^^^^^
ValueError: invalid literal for int() with base 10: '42x'
>>> 3.14 / 0
Traceback (most recent call last):
  File "&LTpython-input-2>", line 1, in &LTmodule>
    3.14 / 0
    ~~~~~^~~
ZeroDivisionError: float division by zero
</code></pre><p>When an exception occurs, the program stops executing and displays the line that caused the error. You also get an error type, such as <code>ValueError</code> and <code>ZeroDivisionError</code> seen in the above example, followed by a message. This may differ for user defined error types.<p>You can implement alternate code branches to be followed for certain types of errors instead of premature end to the program execution. For example, you could allow the user to correct their input data. In some cases, you want the program to end, but display a user friendly message instead of developer friendly traceback.<p>Put the code likely to generate an exception inside a <code>try</code> block and provide alternate paths inside one or more <code>except</code> blocks. Here's an example to get a positive integer number from the user, and continue doing so if the input was invalid.<pre><code class=language-python># try_except.py
from math import factorial

while True:
    try:
        num = int(input('Enter a positive integer: '))
        print(f'{num}! = {factorial(num)}')
        break
    except ValueError:
        print('Not a positive integer, try again')
</code></pre><p>It so happens that both <code>int()</code> and <code>factorial()</code> generate <code>ValueError</code> in the above example. If you wish to take the same alternate path for multiple errors, you can pass a <code>tuple</code> to <code>except</code> instead of a single error type. Here's a sample run:<pre><code class=language-bash>$ python3.13 try_except.py
Enter a positive integer: 3.14
Not a positive integer, try again
Enter a positive integer: hi
Not a positive integer, try again
Enter a positive integer: -2
Not a positive integer, try again
Enter a positive integer: 5
5! = 120
</code></pre><p>You can also capture the error message using the <code>as</code> keyword (which you have seen previously with the <code>import</code> statement, and discussed again in later chapters). Here's an example:<pre><code class=language-python>>>> try:
...     num = 5 / 0
... except ZeroDivisionError as e:
...     print(f'oops something went wrong! the error msg is:\n"{e}"')
... 
oops something went wrong! the error msg is:
"division by zero"
</code></pre><blockquote><p><img alt=info src=./images/info.svg> See <a href=https://docs.python.org/3/library/exceptions.html#bltin-exceptions>docs.python: built-in exceptions</a> for documentation on built-in exceptions.</blockquote><blockquote><p><img alt=warning src=./images/warning.svg> It is not recommended to use <code>except</code> without passing an error type. See <a href=https://stackoverflow.com/q/14797375/4082052>stackoverflow: avoid bare exceptions</a> for details. See also <a href=https://stackoverflow.com/q/18176602/4082052>stackoverflow: get the name of an exception that was raised</a>.</blockquote><blockquote><p><img alt=info src=./images/info.svg> There are static code analysis tools like <a href=https://pypi.org/project/pylint/>pylint</a>, "which looks for programming errors, helps enforcing a coding standard, sniffs for code smells and offers simple refactoring suggestions". See <a href=https://github.com/vinta/awesome-python#code-analysis>awesome-python: code-analysis</a> for more such tools.</blockquote><h2 id=else><a class=header href=#else>else</a></h2><p>The <code>else</code> clause behaves similarly to the <code>else</code> clause seen with loops. If there's no exception raised in the <code>try</code> block, then the code in the <code>else</code> block will be executed. This block should be defined after the <code>except</code> blocks. As per the <a href=https://docs.python.org/3/tutorial/errors.html#handling-exceptions>documentation</a>:<blockquote><p>The use of the <code>else</code> clause is better than adding additional code to the <code>try</code> clause because it avoids accidentally catching an exception that wasn’t raised by the code being protected by the <code>try ... except</code> statement.</blockquote><pre><code class=language-python># try_except_else.py
while True:
    try:
        num = int(input('Enter an integer number: '))
    except ValueError:
        print('Not an integer, try again')
    else:
        print(f'Square of {num} is {num ** 2}')
        break
</code></pre><p>Here's a sample run:<pre><code class=language-bash>$ python3.13 try_except_else.py
Enter an integer number: hi
Not an integer, try again
Enter an integer number: 3.14
Not an integer, try again
Enter an integer number: 42x
Not an integer, try again
Enter an integer number: -2
Square of -2 is 4
</code></pre><h2 id=raise><a class=header href=#raise>raise</a></h2><p>You can manually <code>raise</code> exceptions if needed. It accepts an optional error type, which can be either a built-in or a user defined one (see <a href=https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions>docs.python: User-defined Exceptions</a>). And you can optionally specify an error message. <code>raise</code> by itself re-raises the currently active exception, if any (<code>RuntimeError</code> otherwise).<pre><code class=language-python>>>> def sum2nums(n1, n2):
...     types_allowed = (int, float)
...     if type(n1) not in types_allowed or type(n2) not in types_allowed:
...         raise TypeError('Argument should be an integer or a float value')
...     return n1 + n2
... 
>>> sum2nums(3.14, -2)
1.1400000000000001
>>> sum2nums(3.14, 'a')
Traceback (most recent call last):
  File "&LTpython-input-2>", line 1, in &LTmodule>
    sum2nums(3.14, 'a')
    ~~~~~~~~^^^^^^^^^^^
  File "&LTpython-input-0>", line 4, in sum2nums
    raise TypeError('Argument should be an integer or a float value')
TypeError: Argument should be an integer or a float value
</code></pre><h2 id=finally><a class=header href=#finally>finally</a></h2><p>You can add code in the <code>finally</code> block that should always be the last thing done by the <code>try</code> statement, irrespective of whether an exception has occurred. This should be declared after <code>except</code> and the optional <code>else</code> blocks.<pre><code class=language-python># try_except_finally.py
try:
    num = int(input('Enter a positive integer: '))
    if num < 0:
        raise ValueError
except ValueError:
    print('Not a positive integer, run the program again')
else:
    print(f'Square root of {num} is {num ** 0.5:.3f}')
finally:
    print('\nThanks for using the program, have a nice day')
</code></pre><p>Here are some sample runs when the user enters some value:<pre><code class=language-bash>$ python3.13 try_except_finally.py
Enter a positive integer: -2
Not a positive integer, run the program again

Thanks for using the program, have a nice day
$ python3.13 try_except_finally.py
Enter a positive integer: 2
Square root of 2 is 1.414

Thanks for using the program, have a nice day
</code></pre><p>Here's an example where something goes wrong, but not handled by the <code>try</code> statement. Note that <code>finally</code> block is still executed.<pre><code class=language-bash># here, user presses Ctrl+D instead of entering a value
# you'll get KeyboardInterrupt if the user presses Ctrl+C
$ python3.13 try_except_finally.py
Enter a positive integer: 
Thanks for using the program, have a nice day
Traceback (most recent call last):
  File "/home/learnbyexample/Python/programs/try_except_finally.py",
       line 2, in &LTmodule>
    num = int(input('Enter a positive integer: '))
              ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError
</code></pre><p>See <a href=https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions>docs.python: Defining Clean-up Actions</a> for details like what happens if an exception occurs within an <code>else</code> clause, presence of <code>break/continue/return</code> etc. The documentation also gives examples of where <code>finally</code> is typically used.<h2 id=exercises><a class=header href=#exercises>Exercises</a></h2><ul><li><p>Identify the syntax errors in the following code snippets. Try to spot them manually.</p> <pre><code class=language-ruby># snippet 1:
def greeting()
    print('hello')

# snippet 2:
num = 5
if num = 4:
    print('what is going on?!')

# snippet 3:
greeting = “hi”
</code></pre><li><p>In case you didn't complete the exercises from the <a href=./importing-and-creating-modules.html#importing-your-own-module>Importing your own module</a> section, you should be able to do it now.</p><li><p>Write a function <code>num(ip)</code> that accepts a single argument and returns the corresponding integer or floating-point number contained in the argument. Only <code>int</code>, <code>float</code> and <code>str</code> should be accepted as a valid input data type. Provide custom error messages if the input cannot be converted to a valid number. Examples are shown below:</p> <pre><code class=language-ruby>>>> num(0x1f)
31
>>> num(3.32)
3.32
>>> num(' \t 52 \t')
52
>>> num('3.982e5')
398200.0

# wrong data type
>>> num(['1', '2.3'])
TypeError: not a valid input
# string input that cannot be converted to a valid int/float number
>>> num('foo')
ValueError: could not convert string to int or float
</code></pre></ul></main><nav aria-label="Page navigation"class=nav-wrapper><a aria-label="Previous chapter"class="mobile-nav-chapters previous"title="Previous chapter"aria-keyshortcuts=Left href=installing-modules-and-virtual-environments.html rel=prev> <i class="fa fa-angle-left"></i> </a><a aria-label="Next chapter"class="mobile-nav-chapters next"title="Next chapter"aria-keyshortcuts=Right href=debugging.html rel=next> <i class="fa fa-angle-right"></i> </a><div style="clear: both"></div></nav></div></div><nav aria-label="Page navigation"class=nav-wide-wrapper><a aria-label="Previous chapter"class="nav-chapters previous"title="Previous chapter"aria-keyshortcuts=Left href=installing-modules-and-virtual-environments.html rel=prev> <i class="fa fa-angle-left"></i> </a><a aria-label="Next chapter"class="nav-chapters next"title="Next chapter"aria-keyshortcuts=Right href=debugging.html rel=next> <i class="fa fa-angle-right"></i> </a></nav></div><script>window.playground_copyable = true;</script><script charset=utf-8 src=elasticlunr.min.js></script><script charset=utf-8 src=mark.min.js></script><script charset=utf-8 src=searcher.js></script><script charset=utf-8 src=clipboard.min.js></script><script charset=utf-8 src=highlight.js></script><script charset=utf-8 src=book.js></script><script src=sidebar.js></script>